version: '3.8'

services:
  app:
    image: vivek031/jobs-and-reviews-portal-app:0.0.1.RELEASE
    container_name: jobs-and-review-portal-app-container
    ports:
      - "8081:8080"
    networks:
      - jobsandreviewportal 
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_database:3306/job_raiting_db?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Newuser123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql_database
#        condition: service_healthy

  mysql_database:
    image: mysql:8.0.4
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Newuser123
      MYSQL_DATABASE: job_raiting_db
    ports:
      - "3307:3306"
    networks:
      - jobsandreviewportal 
    volumes:
      - mysql_volume:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pYOUR_PASSWORD_HERE"]
#      timeout: 20s
#      retries: 5 
      
networks:
  jobsandreviewportal:
    driver: bridge
volumes:
  mysql_volume: